export const ADD_MOVIE = "add/movie"
export const DELETE_MOVIE = "delete/movie"
export const EDIT_MOVIE = "edit/movie"
export const FILTER_MOVIE ="filter/movie"
export const ADD_USER = "add/user"
export const DELETE_USER = "delete/user"